### ISSUE TITLE
Getting Error " Caused by: java.lang.NullPointerException: Build Config field cannot have a null parameter "

### ISSUE THREAD

**Issue by VanshVarshney** [dheerajkotwani/HackCovid-19#2]
i am getting error " Caused by: java.lang.NullPointerException: Build Config field cannot have a null parameter " , I Had Imported the code via Git Link In My Android Studio, Can You Tell Me How To Fix This.

![Capture](https://user-images.githubusercontent.com/50292179/78560545-e04c8d80-7833-11ea-8dae-170e5b667293.PNG)

**Comment by dheerajkotwani** [comment]
To Setup the project properly add the following to local.properties under Gradle Scripts
GOOGLE_MAP_KEY="Add your google map api key"

**Comment by VanshVarshney** [comment]
Ok Thanks
