### ISSUE TITLE
Getting Error  java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference

### ISSUE THREAD

**Issue by VanshVarshney** [dheerajkotwani/HackCovid-19#3]
![image](https://user-images.githubusercontent.com/50292179/79038798-ece93100-7bf9-11ea-8513-fa1208bf4838.png)

**Comment by dheerajkotwani** [comment]
Please check if you have given location permissions to the app

**Comment by dheerajkotwani** [comment]
It might not run on the virtual device/emulator try running it on you mobile.

**Comment by VanshVarshney** [comment]
Every permission is given, also not working on real device, 
I just added the GOOGLE_API_KEY In Local.properties 

App is crashing !

**Comment by dheerajkotwani** [comment]
I had checked on various devices its working properly fine.

**Comment by VanshVarshney** [comment]
not working app is getting crashed as mentioned.

the key i entered.
GOOGLE_MAP_KEY="BB:0D:AC:74:D3:21:E1:43:67:71:9B:62:91:AF:A1:66:6E:44:5D:75"
in local.properties

**Comment by dheerajkotwani** [comment]
This is invalid Google map key, google map key is one you can get the google map api developer page starting with "AIza".

**Comment by VanshVarshney** [comment]
Still Error I Changed To New Key.
